version: "3.9"  # optional since v1.27.0
services:
  web_api:
    image: "ychesnok/fintacharts"
    container_name: Fintacharts_Data_Collection
    ports:
      - "5000:8080"
    depends_on: 
      - sql
  sql:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: sql_server2022
    ports: # not actually needed, because the two services are on the same network
      - "1433:1433" 
    environment:
      - ACCEPT_EULA=y
      - MSSQL_SA_PASSWORD=eSk3B2WtPv